namespace OrganizedCrime.PropertyProbe.Model;

public sealed record PropertyPromotionExperimentSnapshot(
    string ProposedPropertyCode,
    string TargetName,
    string TargetPath,
    string Gate,
    bool PreconditionsPassed,
    bool RegistrationPassed,
    bool OwnershipPassed,
    bool PersistencePassed,
    int PropertyCountBefore,
    int PropertyCountAfter,
    int OwnedPropertyCountBefore,
    int OwnedPropertyCountAfter,
    int UnownedPropertyCountBefore,
    int UnownedPropertyCountAfter,
    bool TargetRegisteredAfter,
    bool TargetOwnedAfter,
    bool TargetInOwnedCollectionAfter,
    bool TargetInUnownedCollectionAfter,
    string DocksWarehouseCodeBefore,
    string DocksWarehouseCodeAfter,
    bool DocksWarehouseOwnedBefore,
    bool DocksWarehouseOwnedAfter,
    string? FailureReason)
{
    public static PropertyPromotionExperimentSnapshot Test(
        string gate = "preconditions",
        bool preconditionsPassed = false,
        bool registrationPassed = false,
        bool ownershipPassed = false,
        bool persistencePassed = false,
        string targetName = "Fish Warehouse",
        string targetPath = "Map/Hyland Point/Region_Docks/Fish Warehouse/fishwarehouse",
        int propertyCountBefore = 0,
        int propertyCountAfter = 0,
        int ownedPropertyCountBefore = 0,
        int ownedPropertyCountAfter = 0,
        int unownedPropertyCountBefore = 0,
        int unownedPropertyCountAfter = 0,
        bool targetRegisteredAfter = false,
        bool targetOwnedAfter = false,
        bool targetInOwnedCollectionAfter = false,
        bool targetInUnownedCollectionAfter = false,
        string docksWarehouseCodeBefore = "dockswarehouse",
        string docksWarehouseCodeAfter = "dockswarehouse",
        bool docksWarehouseOwnedBefore = false,
        bool docksWarehouseOwnedAfter = false,
        string? failureReason = null)
    {
        return new PropertyPromotionExperimentSnapshot(
            ProposedPropertyCode: "oc_fishwarehouse",
            TargetName: targetName,
            TargetPath: targetPath,
            Gate: gate,
            PreconditionsPassed: preconditionsPassed,
            RegistrationPassed: registrationPassed,
            OwnershipPassed: ownershipPassed,
            PersistencePassed: persistencePassed,
            PropertyCountBefore: propertyCountBefore,
            PropertyCountAfter: propertyCountAfter,
            OwnedPropertyCountBefore: ownedPropertyCountBefore,
            OwnedPropertyCountAfter: ownedPropertyCountAfter,
            UnownedPropertyCountBefore: unownedPropertyCountBefore,
            UnownedPropertyCountAfter: unownedPropertyCountAfter,
            TargetRegisteredAfter: targetRegisteredAfter,
            TargetOwnedAfter: targetOwnedAfter,
            TargetInOwnedCollectionAfter: targetInOwnedCollectionAfter,
            TargetInUnownedCollectionAfter: targetInUnownedCollectionAfter,
            DocksWarehouseCodeBefore: docksWarehouseCodeBefore,
            DocksWarehouseCodeAfter: docksWarehouseCodeAfter,
            DocksWarehouseOwnedBefore: docksWarehouseOwnedBefore,
            DocksWarehouseOwnedAfter: docksWarehouseOwnedAfter,
            FailureReason: failureReason);
    }
}
