namespace OrganizedCrime.PropertyProbe.Model;

public sealed record RuntimePropertyVerticalSliceSnapshot(
    string ProposedPropertyCode,
    string TargetName,
    ushort CollectionId,
    bool ServerManagerPresent,
    bool ServerAvailable,
    bool TemporaryRootCreated,
    bool NetworkObjectPresent,
    bool PropertyPresent,
    bool IdentityConfigured,
    bool PropertyRegistered,
    bool RuntimeNetworkRegistrationPassed,
    int PropertyCountBefore,
    int PropertyCountAfter,
    bool TargetInProperties,
    bool TargetInUnownedProperties,
    bool TargetInOwnedProperties,
    bool PropertyNetworkObjectResolved,
    bool NetworkInitializeAttempted,
    bool NetworkInitializePassed,
    bool PropertyNetworked,
    bool PropertyClientInitialized,
    bool PropertyServerInitialized,
    bool PropertySpawned,
    bool SpawnAttempted,
    bool SpawnPassed,
    bool DespawnAttempted,
    bool DespawnPassed,
    string NetworkState,
    int ObjectId,
    int PrefabId,
    ushort SpawnableCollectionId,
    bool BucketCleanupAttempted,
    bool BucketCleanupPassed,
    bool TemporaryObjectDestroyed,
    bool AuthoredCollectionUnchanged,
    bool DocksNetworkIdentityUnchanged,
    bool OwnershipAttempted,
    bool PersistenceAttempted,
    bool SaveAttempted,
    string Gate,
    string? FailureReason)
{
    public bool CleanupPassed =>
        (!DespawnAttempted || DespawnPassed) &&
        (!BucketCleanupAttempted || BucketCleanupPassed) &&
        (!BucketCleanupAttempted || TemporaryObjectDestroyed);

    public static RuntimePropertyVerticalSliceSnapshot Test(
        bool propertyRegistered = false,
        bool networkInitializePassed = false,
        bool spawnPassed = false,
        bool cleanupPassed = false)
    {
        return new RuntimePropertyVerticalSliceSnapshot(
            ProposedPropertyCode: "oc_fishwarehouse",
            TargetName: "Fish Warehouse",
            CollectionId: 65000,
            ServerManagerPresent: true,
            ServerAvailable: true,
            TemporaryRootCreated: propertyRegistered,
            NetworkObjectPresent: propertyRegistered,
            PropertyPresent: propertyRegistered,
            IdentityConfigured: propertyRegistered,
            PropertyRegistered: propertyRegistered,
            RuntimeNetworkRegistrationPassed: networkInitializePassed,
            PropertyCountBefore: 13,
            PropertyCountAfter: propertyRegistered ? 14 : 13,
            TargetInProperties: propertyRegistered,
            TargetInUnownedProperties: propertyRegistered,
            TargetInOwnedProperties: false,
            PropertyNetworkObjectResolved: networkInitializePassed,
            NetworkInitializeAttempted: propertyRegistered,
            NetworkInitializePassed: networkInitializePassed,
            PropertyNetworked: networkInitializePassed,
            PropertyClientInitialized: false,
            PropertyServerInitialized: networkInitializePassed,
            PropertySpawned: spawnPassed,
            SpawnAttempted: networkInitializePassed,
            SpawnPassed: spawnPassed,
            DespawnAttempted: spawnPassed,
            DespawnPassed: cleanupPassed,
            NetworkState: spawnPassed ? "Spawned" : "Unset",
            ObjectId: spawnPassed ? 1 : 0,
            PrefabId: 0,
            SpawnableCollectionId: networkInitializePassed ? (ushort)65000 : (ushort)0,
            BucketCleanupAttempted: cleanupPassed,
            BucketCleanupPassed: cleanupPassed,
            TemporaryObjectDestroyed: cleanupPassed,
            AuthoredCollectionUnchanged: true,
            DocksNetworkIdentityUnchanged: true,
            OwnershipAttempted: false,
            PersistenceAttempted: false,
            SaveAttempted: false,
            Gate: spawnPassed && cleanupPassed ? "vertical-slice-passed" : "vertical-slice-partial",
            FailureReason: null);
    }
}
